# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63a4515796a308a5eae852149cafce1f8404f0da4808bd5842cc317e770241f1d6c3b4e9d4bf7db3671cf4fcd76efcbe75220fba9c5e8bd773737dc4ad988f53

test:
  secret_key_base: 84225743fc4d02486031f02b5d1b637b569b621e43a6a062bc385b5eb105b70821a210786ae9a6db90af3ea6af92c52d8f35fa906057a2bcaa4dc6791bf566c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
